[{
    "POI_ID": "42",
    "POI_Latitude": 35.373927,
    "POI_Longitude": -83.222020,
    "POI_Title": "Backstreet Airsoft",
    "POI_Description": "Backstreet Airsoft is the ultimate airsoft outfitter as they sell airsoft guns, accessories, military surplus, tactical gear, and sporting goods. Whether you are new to airsoft or are seasoned in battle, airsoft battles are a blast (pun intended) and promote physical activity. Stop by Backstreet Airsoft at 567 Mill Street for all of your airsoft needs.",
    "POI_Image1": "BackstreetAirsoft.JPG",
    "POI_Image2": "BackstreetAirsoft1.JPG",
    "POI_Image3": "BackstreetAirsoft4.JPG",
    "POI_Image4": "BackstreetAirsoft5.JPG",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "567 Mill St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "(828) 631-9985",
    "POI_URL": "",
    "POI_Category": "5",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "43",
    "POI_Latitude": 35.373781,
    "POI_Longitude": -83.222610,
    "POI_Title": "Hooker's Fly Shop",
    "POI_Description": "Hooker's Fly Shop carries fly fishing supplies such as flies, waders, fly rods, and fly fishing accessories. Hooker's Fly Shop also guides fly fishing trips in the area and in the Smokys. Hooker's Fly Shop can take you on wade trips, float trips, overnight trips and Hooker's will provide all of the equipment you need on your adventure!",
    "POI_Image1": "Hookers6.JPG",
    "POI_Image2": "Hookers.JPG",
    "POI_Image3": "Hookers1.JPG",
    "POI_Image4": "Hookers2.JPG",
    "POI_Image5": "Hookers4.JPG",
    "POI_Image6": "Hookers5.jpg",
    "POI_Address1": "546 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "(828) 587-4665",
    "POI_URL": "http://www.hookersflyshop.com/",
    "POI_Category": "5",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "95",
    "POI_Latitude": 35.373919,
    "POI_Longitude": -83.220476,
    "POI_Title": "Innovation Brewing",
    "POI_Description": "Innovation Brewing is a small brewpub lucky enough to be nestled into the Tuckasseegee River Valley. We take pride in making the best ales possible to provide this amazing little town with a brewpub to be proud of. We have a large variety of beers available for palates of all preferences. We have 22 house made beers, 10 of which are always around and the rest are always changing and rotating. We also have a delicious house made ginger ale made with fresh organic ginger available for the kiddos or anyone looking for a refreshing non-alcoholic beverage. We offer live music on Saturdays and have a delicious food truck called Cosmic Carryout on premises everyday. Come by and check us out we are certain you'll love it! Fermentation. Experimentation. Innovation.",
    "POI_Image1": "InnovationBrewing.jpg",
    "POI_Image2": "InnovationBrewing1.jpg",
    "POI_Image3": "InnovationBrewing2.jpg",
    "POI_Image4": "InnovationBrewing3.JPG",
    "POI_Image5": "InnovationBrewing4.JPG",
    "POI_Image6": "",
    "POI_Address1": "414 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-9678",
    "POI_URL": "http://www.innovation-brewing.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "86",
    "POI_Latitude": 35.374146,
    "POI_Longitude": -83.218792,
    "POI_Title": "Dodie Auction",
    "POI_Description": "Whether you live here or you're just visiting, you can't go to downtown Sylva, NC without stopping by Dodie's Store. Visit Dodie's Store and Auction to find great antiques and treasures.  Visit her facebook page to watch for upcoming auctions and events.",
    "POI_Image1": "Dodies.jpeg",
    "POI_Image2": "Dodie2.jpeg",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "482 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-3634",
    "POI_URL": "https://www.dodieallen.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "104",
    "POI_Latitude": 35.374146,
    "POI_Longitude": -83.218792,
    "POI_Title": "Jackson County Chamber of Commerce",
    "POI_Description": "The Jackson County Chamber of Commerce serves as the driving force behind the county's prosperous and diverse business community. At 450 members and growing, the Chamber's mission is to Improve the welfare and quality of life of Jackson County citizens through smart economic growth. The chamber is located at 773 West Main Street in the historic Hooper House in downtown Sylva. Also located in the Hooper House is the Jackson County Visitor Center and the Heritage Gallery. Chamber hours are Monday through Friday 9:00 a.m. to 5:00 p.m.",
    "POI_Image1": "Chamber.jpg",
    "POI_Image2": "Chamber1.JPG",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "773 West Main Street",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "(828)-586-2155",
    "POI_URL": "",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}]