[{
    "POI_ID": "81",
    "POI_Latitude": 35.373879,
    "POI_Longitude": -83.220297,
    "POI_Title": "Papou's Wine Shop",
    "POI_Description": "A locally owned shop that has been in business for 9 years. They offer a large selection of wines from around the world. Customers may come in for a bottle to take home, or they can sit and enjoy a glass of wine at our wine bar. Papou's offers duplicate discounts on cases of wine needed for weddings, and parties, etc. They have regularly scheduled wine tastings and other classes for individuals interested in learning more about wine.\r\n",
    "POI_Image1": "Papous1.JPG",
    "POI_Image2": "Papous.JPG",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "414 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "(828)-586-6300",
    "POI_URL": "https://www.wcu.edu",
    "POI_Category": "3",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "82",
    "POI_Latitude": 35.373916,
    "POI_Longitude": -83.222540,
    "POI_Title": "Heinzelmannchen Brewery",
    "POI_Description": "Established in 2004, Dieter Kuhn, Certified Braumeister entices your palate and complements what's on your plate by creating Traditional German Ales plus a few other creations!  Also handcrafted are non-alcoholic Draft Root Beer and Birch Beer made with organic cane sugar.  Local, handmade Soft Pretzels are available for purchase. Feel free to bring in a picnic or take-out from one of our downtown food establishments and play cards, jenga, checkers, chess, etc.  Dog and Kid Friendly, we look forward to seeing you soon at Your Gnometown Brewery!\r\n",
    "POI_Image1": "Heinzelmannchen.jpg",
    "POI_Image2": "",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "545 Mill St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-4466",
    "POI_URL": "http://www.madbatterfoodandfilm.com/",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}
,
{
    "POI_ID": "101",
    "POI_Latitude": 35.373661,
    "POI_Longitude": -83.224309,
    "POI_Title": "Signature Brew Coffee Company",
    "POI_Description": "Signature Brew Coffee Company is a local favorite whose menu has coffee, beer, wine, and desserts, as well as gourmet sandwiches and meals all served in a lovely home-like and welcoming atmosphere.",
    "POI_Image1": "SignatureBrew1.jpg",
    "POI_Image2": "SignatureBrew2.jpg",
    "POI_Image3": "Signature Brew Photo.jpeg",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "633 W Main St,",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-587-6300",
    "POI_URL": "http://www.signaturebrew.net",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
},
{
    "POI_ID": "97",
    "POI_Latitude": 35.373669,
    "POI_Longitude": -83.221780,
    "POI_Title": "Evolution Wine Kitchen",
    "POI_Description": "Evolution is a restaurant, wine bar, and bottle shop. They sell the infused olive oils and balsamic vinegars that are used in the recipes featured on their menu. Hours are Monday through Wednesday 7 a.m. to 9 p.m. and Thursday through Saturday 7 a.m. to midnight.",
    "POI_Image1": "EvolutionWineKitchen.png",
    "POI_Image2": "EvolutionWineKitchen1.jpg",
    "POI_Image3": "EvolutionWineKitchen2.jpg",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "506 W Main St,",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-9856",
    "POI_URL": "http://www.evolutionwinekitchen.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
},
{
    "POI_ID": "96",
    "POI_Latitude": 35.372940,
    "POI_Longitude": -83.223345,
    "POI_Title": "City Lights Café",
    "POI_Description": "City Lights Café has comfy seating, an outdoor patio and an awesome indie bookstore up above. Their menu offers dairy free options, vegetarian options, hormone free chicken, organic greens, and local goat cheese, seasonal local produce, locally brewed beer including gluten free beer, and locally roasted coffee.",
    "POI_Image1": "CityLights4.jpeg",
    "POI_Image2": "",
    "POI_Image3": "CityLights1.jpg",
    "POI_Image4": "CityLights2.jpg",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "3 E Jackson St,",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-587-2233",
    "POI_URL": "http://www.citylightscafe.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "95",
    "POI_Latitude": 35.373919,
    "POI_Longitude": -83.220476,
    "POI_Title": "Innovation Brewing",
    "POI_Description": "Innovation Brewing is a small brewpub lucky enough to be nestled into the Tuckasseegee River Valley. We take pride in making the best ales possible to provide this amazing little town with a brewpub to be proud of. We have a large variety of beers available for palates of all preferences. We have 22 house made beers, 10 of which are always around and the rest are always changing and rotating. We also have a delicious house made ginger ale made with fresh organic ginger available for the kiddos or anyone looking for a refreshing non-alcoholic beverage. We offer live music on Saturdays and have a delicious food truck called Cosmic Carryout on premises everyday. Come by and check us out we are certain you'll love it! Fermentation. Experimentation. Innovation.",
    "POI_Image1": "InnovationBrewing.jpg",
    "POI_Image2": "InnovationBrewing1.jpg",
    "POI_Image3": "InnovationBrewing2.jpg",
    "POI_Image4": "InnovationBrewing3.JPG",
    "POI_Image5": "InnovationBrewing4.JPG",
    "POI_Image6": "",
    "POI_Address1": "414 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-9678",
    "POI_URL": "http://www.innovation-brewing.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}]