[{
    "POI_ID": "92",
    "POI_Latitude": 35.373818,
    "POI_Longitude": -83.223633,
    "POI_Title": "Melissa's Backstreet Takeout",
    "POI_Description": "Melissa's Backstreet Takeout offers great food with an Asian flair. This takeout only restaurant is a local hotspot providing simple, fast and fresh food. Find them on Facebook under Melissa's Backstreet Takeout or on their website www.Backstreettakeout.com for a full menu and weekly specials. \r\n",
    "POI_Image1": "MelissasBackstreetTakeout2.JPG",
    "POI_Image2": "MelissasBackStreetTakeout1.JPG",
    "POI_Image3": "MelissasBackstreetTakeout.JPG",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "605 Mill St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "",
    "POI_URL": "http://www.backstreettakeout.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "93",
    "POI_Latitude": 35.373394,
    "POI_Longitude": -83.224126,
    "POI_Title": "Mad Batter",
    "POI_Description": "Mad Batter is located in beautiful downtown Sylva and serves lunch, and dinner Monday through Saturday, and brunch on Sunday. Thursday through Saturday enjoy dinner while watching a free movie. The food is made with love, local and organic ingredients, including local produce and eggs. Enjoy house made sandwiches, wraps, meatless burgers, soups, salads, appetizers, and desserts.",
    "POI_Image1": "MadBatter4.jpg",
    "POI_Image2": "MadBatter3.PNG",
    "POI_Image3": "MadBatter1.JPG",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "617 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "(828) 586-3555",
    "POI_URL": "http://www.madbatterfoodandfilm.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "94",
    "POI_Latitude": 35.373662,
    "POI_Longitude": -83.224324,
    "POI_Title": "Guadalupe Cafe",
    "POI_Description": "Guadalupe Cafe obtains all available produce, meat and cheese locally from independent farms. They always use local, free-range farm eggs. All dairy, poultry and meats are free of dodgy stuff like artificial flavors and growth hormones, and shrimp and other seafood are sustainably sourced when available. The food is hand-made with wholesome, natural, mostly organic ingredients and love!",
    "POI_Image1": "Guadalupe.JPG",
    "POI_Image2": "",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "606 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "(828) 586-9877",
    "POI_URL": "http://www.guadalupecafe.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "95",
    "POI_Latitude": 35.373919,
    "POI_Longitude": -83.220476,
    "POI_Title": "Innovation Brewing",
    "POI_Description": "Innovation Brewing is a small brewpub lucky enough to be nestled into the Tuckasseegee River Valley. We take pride in making the best ales possible to provide this amazing little town with a brewpub to be proud of. We have a large variety of beers available for palates of all preferences. We have 22 house made beers, 10 of which are always around and the rest are always changing and rotating. We also have a delicious house made ginger ale made with fresh organic ginger available for the kiddos or anyone looking for a refreshing non-alcoholic beverage. We offer live music on Saturdays and have a delicious food truck called Cosmic Carryout on premises everyday. Come by and check us out we are certain you'll love it! Fermentation. Experimentation. Innovation.",
    "POI_Image1": "InnovationBrewing1.jpg",
    "POI_Image2": "InnovationBrewing.jpg",
    "POI_Image3": "InnovationBrewing2.jpg",
    "POI_Image4": "InnovationBrewing3.JPG",
    "POI_Image5": "InnovationBrewing4.JPG",
    "POI_Image6": "",
    "POI_Address1": "414 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-9678",
    "POI_URL": "http://www.innovation-brewing.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
},
{
    "POI_ID": "96",
    "POI_Latitude": 35.372940,
    "POI_Longitude": -83.223345,
    "POI_Title": "City Lights Cafe",
    "POI_Description": "City Lights Cafe has comfy seating, an outdoor patio and an awesome indie bookstore up above. Their menu offers dairy free options, vegetarian options, hormone free chicken, organic greens, and local goat cheese, seasonal local produce, locally brewed beer including gluten free beer, and locally roasted coffee.",
    "POI_Image1": "CityLights4.jpeg",
    "POI_Image2": "CityLights2.jpg",
    "POI_Image3": "CityLights1.jpg",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "3 E Jackson St,",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-587-2233",
    "POI_URL": "http://www.citylightscafe.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
},
{
    "POI_ID": "97",
    "POI_Latitude": 35.373669,
    "POI_Longitude": -83.221780,
    "POI_Title": "Evolution Wine Kitchen",
    "POI_Description": "Evolution is a restaurant, wine bar, and bottle shop. They sell the infused olive oils and balsamic vinegars that are used in the recipes featured on their menu. Hours are Monday through Wednesday 7 a.m. to 9 p.m. and Thursday through Saturday 7 a.m. to midnight.",
    "POI_Image1": "EvolutionWineKitchen.png",
    "POI_Image2": "EvolutionWineKitchen1.jpg",
    "POI_Image3": "EvolutionWineKitchen2.jpg",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "506 W Main St,",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-9856",
    "POI_URL": "http://www.evolutionwinekitchen.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}
,
{
    "POI_ID": "98",
    "POI_Latitude": 35.373621,
    "POI_Longitude": -83.224082,
    "POI_Title": "Lulu's On Main",
    "POI_Description": "Lulu's On Main is known for its out of the ordinary eclectic fare, great service, and consistency, provided in an edgy retro atmosphere. Lulu's menu features favorites like certified Black Angus hand cut steaks, fresh North Carolina seafood, vegetarian tofu stir-fry and pasta ala greque. Southern Living Magazine says, 'Lulu's is our favorite restaurant in the region.'",
    "POI_Image1": "LulusCafe.jpg",
    "POI_Image2": "LulusCafe1.jpg",
    "POI_Image3": "LulusCafe2.jpg",
    "POI_Image4": "LulusCafe3.jpg",
    "POI_Image5": "LulusCafe4.jpg",
    "POI_Image6": "",
    "POI_Address1": "612 W Main St,",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-8989",
    "POI_URL": "http://www.lulusonmain.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
},
{
    "POI_ID": "99",
    "POI_Latitude": 35.371486,
    "POI_Longitude": -83.205622,
    "POI_Title": "The Coffee Shop",
    "POI_Description": "The Coffee Shop is Sylva's local hometown diner with great service, great pie and a friendly staff. They have daily specials like turkey and dressing or chicken and dumplings. For pictures of their menu and daily specials, visit their Facebook page.",
    "POI_Image1": "",
    "POI_Image2": "",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "385 E Main St,",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-2013",
    "POI_URL": "https://www.facebook.com/pages/The-Coffee-Shop/225830537427351",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
},
{
    "POI_ID": "100",
    "POI_Latitude": 35.371486,
    "POI_Longitude": -83.205622,
    "POI_Title": "Eric's Fresh Fish Market",
    "POI_Description": "Eric's Fresh Fish Market provides fresh fish that you can buy and eat with confidence for your weekend meals. The seafood is provided by Inland Seafood of Atlanta who also supplies seafood to Whole Foods, Earth Fare, Publix and Kroger.",
    "POI_Image1": "EricsFreshFish.jpg",
    "POI_Image2": "EricsFreshFish1.jpg",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "609 Mill St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-587-3474",
    "POI_URL": "http://www.ericsfreshfishmarket.com",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "banner",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}
,
{
    "POI_ID": "101",
    "POI_Latitude": 35.373661,
    "POI_Longitude": -83.224309,
    "POI_Title": "Signature Brew Coffee Company",
    "POI_Description": "Signature Brew Coffee Company is a local favorite whose menu has coffee, beer, wine, and desserts, as well as gourmet sandwiches and meals all served in a lovely home-like and welcoming atmosphere.",
    "POI_Image1": "SignatureBrew2.jpg",
    "POI_Image2": "Signature Brew Photo.jpeg",
    "POI_Image3": "SignatureBrew1.jpg",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "633 W Main St,",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-587-6300",
    "POI_URL": "http://www.signaturebrew.net",
    "POI_Category": "2",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}]