[{
    "POI_ID": "24",
    "POI_Latitude": 35.374019,
    "POI_Longitude": -83.226567,
    "POI_Title": "Blue Ridge Inn",
    "POI_Description": "The Blue Ridge Inn has been recently renovated and excels in customer service. Whether your TV remote needs new batteries or you need directions around the beautiful town of Sylva, the employees are there to help! The Blue Ridge Inn is one of the only hotels in the area that is pet friendly and is located conveniently in downtown Sylva.",
    "POI_Image1": "BlueRidgeInn2.jpg",
    "POI_Image2": "BlueRidgeInn3.jpg",
    "POI_Image3": "BlueRidgeInn1.jpg",
    "POI_Image4": "BlueRidgeInn.jpg",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "756 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-2123",
    "POI_URL": "",
    "POI_Category": "4",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}]