[{
    "POI_ID": "66",
    "POI_Latitude": 35.374228,
    "POI_Longitude": -83.218689,
    "POI_Title": "Paradise Music",
    "POI_Description": "Musical instrument sales, service, rentals and repairs, trades gear, and has new and used instruments in stock, as well as strings and musical accessories.\r\n",
    "POI_Image1":"ParadiseMusic.JPG",
    "POI_Image2": "ParadiseMusic1.JPG",
    "POI_Image3": "ParadiseMusic4.JPG",
    "POI_Image4": "ParadiseMusic7.JPG",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "325 West Main Street",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-3444",
    "POI_URL": "http://www.paradisemusicnc.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "http://localhost:33069/Images/Pictures_of_Businesses/ParadiseMusic.JPG",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "67",
    "POI_Latitude": 35.373400,
    "POI_Longitude": -83.223230,
    "POI_Title": "In Your Ear Music Emporium",
    "POI_Description": "In Your Ear Music is a privately owned music emporium that includes a smokeshop as well as vape gear. They custom tailor our customer's shopping experience to their personal needs and style. They carry a variety of merchandise from cd's to clothing to local and handmade glass blown pipes. In Your Ear Music has proudly been serving Sylva and surrounding communities since 1994.\r\n",
    "POI_Image1": "InYourEar1.JPG",
    "POI_Image2": "InYourEar2.JPG",
    "POI_Image3": "InYourEar6.JPG",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "573 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-6404",
    "POI_URL": "http://www.inyourearmusic.net",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "68",
    "POI_Latitude": 35.373732,
    "POI_Longitude": -83.222207,
    "POI_Title": "Friends of the Library Used Bookstore",
    "POI_Description": "This used bookstore offers affordable reading material for all and facilitates public support of the library by selling donated books and other media. Friends of the Library has every genre you can think of, from gardening and cookbooks to sci-fi and western to religion, health and travel. Friends of the Library also has large print books and books on CD and cassette.",
    "POI_Image1": "LibraryFriends.jpg" ,
    "POI_Image2": "LibraryFriends1.jpg",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "536 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-6404",
    "POI_URL": "http://www.Fojcml.org",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "69",
    "POI_Latitude": 35.373567,
    "POI_Longitude": -83.222446,
    "POI_Title": "Harry Alter Books",
    "POI_Description": "Harry Alter Books specializes in nonfiction collector's books. The store holds more than 20,000 books ranging in genres of history, political science, art, architecture, and local genres.",
    "POI_Image1": "HarryAlter.jpg",
    "POI_Image2": "HarryAlter1.jpg",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "528 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-9070",
    "POI_URL": "http://Www.harryalterbooks.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "70",
    "POI_Latitude": 35.374110,
    "POI_Longitude": -83.218771,
    "POI_Title": "Arsenal Artifacts & Prints, Inc.",
    "POI_Description": "Arsenal Artifacts & Prints specializes in fine custom framework using the industry's top of the line materials. From stretch canvas to historical documents, they can frame it all! Arsenal Artifacts is nationally known for their collection of Civil War Relics and stocks prints of artists such as John Paul Strain and John Warr.",
    "POI_Image1":"ArsenalArtifacts.JPG",
    "POI_Image2": "ArsenalArtifacts1.JPG",
    "POI_Image3": "ArsenalArtifacts3.JPG",
    "POI_Image4":"",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "540 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-1061",
    "POI_URL": "http://www.arsenalartifacts.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "71",
    "POI_Latitude": 35.373917,
    "POI_Longitude": -83.222542,
    "POI_Title": "Survival Pride",
    "POI_Description": "Survival Pride is clothing with a Twist of Mystery and History. The designs on clothing that empowers them and stands for what the person believes in!",
    "POI_Image1": "SurvivalPride.JPG",
    "POI_Image2": "SurvivalPride1.JPG",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "551 Mill St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-6100",
    "POI_URL": "http://www.survivalpride.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "72",
    "POI_Latitude": 35.373786,
    "POI_Longitude": -83.223309,
    "POI_Title": "Jacksons General Store",
    "POI_Description": "Jacksons General Store carries everything you would expect a general store to have, including Carhartt, Pandora jewelry, candy, kitchen gadgets, Yeti coolers, gift items, greeting cards, women's clothing, Vera Bradley, food items like jams, pickles and jellies, and Tervis Tumblers.",
    "POI_Image1": "JacksonsGeneral.JPG",
    "POI_Image2": "JacksonsGeneral1.JPG",
    "POI_Image3": "JacksonsGeneral2.JPG",
    "POI_Image4": "JacksonsGeneral3.JPG",
    "POI_Image5": "JacksonsGeneral4.JPG",
    "POI_Image6": "",
    "POI_Address1": "582 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-9600",
    "POI_URL": "",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "73",
    "POI_Latitude": 35.374145,
    "POI_Longitude": -83.218792,
    "POI_Title": "Livingston's Photo",
    "POI_Description": "Livingston's Photo does custom framing, digital printing, and passports, as well as carrying decor items, puzzles, prints and collector's items.",
    "POI_Image1": "Livingston'sPhoto.JPG",
    "POI_Image2": "LivingstonsPhoto1.JPG",
    "POI_Image3": "LivingstonsPhoto2.JPG",
    "POI_Image4": "LivingstonsPhoto3.JPG",
    "POI_Image5": "LivingstonsPhoto4.JPG",
    "POI_Image6": "",
    "POI_Address1": "526 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-2814",
    "POI_URL": "",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "74",
    "POI_Latitude": 35.373578,
    "POI_Longitude": -83.222641,
    "POI_Title": "Hooker's Fly Shop",
    "POI_Description": "Hooker's Fly Shop carries fly fishing supplies such as flies, waders, fly rods, and fly fishing accessories. Hooker's Fly Shop also guides fly fishing trips in the area and in the Smokies. Hooker's Fly Shop can take you on wade trips, float trips, overnight trips and Hooker's will provide all of the equipment you need on your adventure!",
    "POI_Image1": "Hookers.JPG",
    "POI_Image2": "Hookers1.JPG",
    "POI_Image3": "Hookers2.JPG",
    "POI_Image4": "Hookers4.JPG",
    "POI_Image5": "Hookers5.jpg",
    "POI_Image6": "Hookers6.JPG",
    "POI_Address1": "546 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-587-4665",
    "POI_URL": "http://www.Hookersflyshop.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "75",
    "POI_Latitude": 35.373583,
    "POI_Longitude": -83.223290,
    "POI_Title": "Blackrock Outdoor Center",
    "POI_Description": "Blackrock Outdoor Center has all of your outdoor needs. Whether you are going hiking, fishing, playing disc golf, or walking your dog, everything you could need is at Blackrock. Some merchandise includes outdoor gear, fly fishing equipment, men's and women's clothing, sandals, hiking boots and shoes, dog accessories, disc golf equipment, tents, packs, sunglasses, water bottles, water purification systems, camelbacks and bladders, maps of the area, maps of hiking trails and fishing spots, informational books, sunscreen, and local tees.",
    "POI_Image1": "Blackrock.JPG",
    "POI_Image2": "Blackrock1.JPG",
    "POI_Image3": "Blackrock2.JPG",
    "POI_Image4": "Blackrock3.JPG",
    "POI_Image5": "Blackrock4.JPG",
    "POI_Image6": "Blackrock5.JPG",
    "POI_Address1": "570 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-4453",
    "POI_URL": "",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "76",
    "POI_Latitude": 35.373899,
    "POI_Longitude": -83.224519,
    "POI_Title": "The Jewelry Outlet",
    "POI_Description": "The Jewelry Outlet buys, sells, and trades jewelry as well as does repairs.",
    "POI_Image1": "JewelryOutlet.JPG",
    "POI_Image2": "JewelryOutlet1.JPG",
    "POI_Image3": "JewelryOutlet2.JPG",
    "POI_Image4": "JewelryOutlet3.JPG",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "648 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-4599",
    "POI_URL": "",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "77",
    "POI_Latitude": 35.373618,
    "POI_Longitude": -83.224015,
    "POI_Title": "Hollifield Jewelers",
    "POI_Description": "Hollifield Jewelers is a complete jewelry store owned by a third generation jeweler. Hollifield Jewelers is here for all of your jewelry and service needs. From custom designing jewelry using CAD technology, to laser repairing your eyeglasses, to changing your watch battery, Hollifield Jewelers has all of your jewelry needs and will provide them with exceptional customer service. Hollifield Jewelers also does watch-making, engraving, carries 5 lines of watches and has designer rings, necklaces, and bracelets.",
    "POI_Image1": "HollifieldJewelers6.jpg",
    "POI_Image2": "HollifieldJewelers.JPG",
    "POI_Image3": "HollifieldJewelers1.jpg",
    "POI_Image4": "HollifieldJewelers2.JPG",
    "POI_Image5": "HollifieldJewelers3.jpg",
    "POI_Image6": "HollifieldJewelers4.JPG",
    "POI_Address1": "600 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-4274",
    "POI_URL": "",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "78",
    "POI_Latitude": 35.372845,
    "POI_Longitude": -83.224477,
    "POI_Title": "Nichol's House",
    "POI_Description": "The Nichol's House specializes in fine antiques and linens. The inventory is always changing and new treasures arrive all the time.",
    "POI_Image1": "NicholsHouse.jpg",
    "POI_Image2": "NicholsHouse1.jpg",
    "POI_Image3": "NicholsHouse2.jpg",
    "POI_Image4": "NicholsHouse3.jpg",
    "POI_Image5": "NicholsHouse4.jpg",
    "POI_Image6": "",
    "POI_Address1": "83 Landis St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-0500",
    "POI_URL": "",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "79",
    "POI_Latitude": 35.373667,
    "POI_Longitude": -83.225206,
    "POI_Title": "It's By Nature",
    "POI_Description": "A contemporary and traditional fine art and craft gallery, featuring the works of more than 170 American artists with a concentration on the Southern Highland Mountain region. We represent artists in the mediums of jewelry, ceramics, woodworking, leather, fiber, glass, paper, photography, original paintings and Giclee reproductions. We provide art for everyday living and gifts to serve every occasion. We are 100% American Made and support the preservation of the American craftsmen and quality handmade American craft.",
    "POI_Image1": "ItsByNature1.JPG",
    "POI_Image2": "ItsByNature.JPG",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "678 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-3020",
    "POI_URL": "https://www.itsbynature.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "80",
    "POI_Latitude": 35.373568,
    "POI_Longitude": -83.222446,
    "POI_Title": "Humanite'",
    "POI_Description": "Humanite' carries fun and fashionable women's clothing, and 10 percent of all sales go to charity. Humanite carries clothing, shoes, jewelry and accessories in a great atmosphere.",
    "POI_Image1": "Humanite.JPG",
    "POI_Image2": "Humanite1.JPG",
    "POI_Image3": "Humanite2.JPG",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "530 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-1599",
    "POI_URL": "https://www.shophumanite.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "81",
    "POI_Latitude": 35.372940,
    "POI_Longitude": -83.223345,
    "POI_Title": "City Lights Bookstore",
    "POI_Description": "City Lights Bookstore is tucked in the heart of the southern Appalachian Mountains. Our goal is to share the literature of the region with the world, and the world of books with our community.",
    "POI_Image1": "CityLightsBookstore.jpg",
    "POI_Image2": "CityLightsBookstore1.JPG",
    "POI_Image3": "CityLightsBookstore2.JPG",
    "POI_Image4": "CityLightsBookstore3.JPG",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "3 E Jackson St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-9499",
    "POI_URL": "https://www.citylightsnc.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "82",
    "POI_Latitude": 35.373906,
    "POI_Longitude": -83.224967,
    "POI_Title": "Peebles",
    "POI_Description": "Peebles is a department store found in many small towns. Peebles is known for their good deals, nice selection, and great customer service!",
    "POI_Image1": "",
    "POI_Image2": "",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "670 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-631-3201",
    "POI_URL": "https://www.stagestores.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "83",
    "POI_Latitude": 35.373578,
    "POI_Longitude": -83.223187,
    "POI_Title": "SassyFrass Consignment",
    "POI_Description": "SassyFrass Consignment has an enormous variety of antiques and home goods as well as funky jewelry and treasures.",
    "POI_Image1": "SassyFrass.JPG",
    "POI_Image2": "SassyFrass1.JPG",
    "POI_Image3": "SassyFrass2.JPG",
    "POI_Image4": "SassyFrass3.jpg.png",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "581 W Main St.",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-3600",
    "POI_URL": "https://www.facebook.com/sassyfrassconsignment",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "84",
    "POI_Latitude": 35.373780,
    "POI_Longitude": -83.222900,
    "POI_Title": "Motion Makers Bicycles of Sylva",
    "POI_Description": "A retail and full-service bike shop providing an unmatched experience to the customer in their pursuit of bicycle buying and riding in western NC. Come see us at 36 Allen Street, Sylva NC or call us at 828 586-6925.",
    "POI_Image1": "MotionMakers.JPG",
    "POI_Image2": "MotionMakers1.JPG",
    "POI_Image3": "MotionMakers2.JPG",
    "POI_Image4": "MotionMakers4.JPG",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "36 Allen Street",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-6925",
    "POI_URL": "https://www.motionmakers.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "85",
    "POI_Latitude": 35.3373618,
    "POI_Longitude": -83.224015,
    "POI_Title": "B&B Gifts and Interiors",
    "POI_Description": "B&B Gifts and Interiors carries gifts for all ages including lotions, candles, jewelry and some Western Carolina University things. Some of their top brands are Lilly Pulitzer, Melissa & Doug, Mud Pie, Tripp Candles, and Aspen Bay Candles.",
    "POI_Image1": "B&B.jpg",
    "POI_Image2": "B&B2.JPG",
    "POI_Image3": "B&B1.JPG",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "594 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-1507",
    "POI_URL": "https://www.facebook.com/pages/B-B-Gifts-and-Interiors/206792182696535",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "86",
    "POI_Latitude": 35.303520,
    "POI_Longitude": -83.222000,
    "POI_Title": "Dodie Auction",
    "POI_Description": "Whether you live here or you're just visiting, you can't go to downtown Sylva, NC without stopping by Dodie's Store. Visit Dodie's Store and Auction to find great antiques and treasures. Visit her facebook page to watch for upcoming auctions and events.",
    "POI_Image1": "Dodies.jpeg",
    "POI_Image2": "Dodie2.jpeg",
    "POI_Image3": "",
    "POI_Image4": "",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "482 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-3634",
    "POI_URL": "https://www.dodieallen.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}, {
    "POI_ID": "87",
    "POI_Latitude": 35.373662,
    "POI_Longitude": -83.224324,
    "POI_Title": "Dixie Mae",
    "POI_Description": "A Vintage Market with an eclectic flair filled with Antiques and Vintage Treasures for your Unique Home, Garden, and Gift.",
    "POI_Image1": "DixieMaes.jpg",
    "POI_Image2": "DixieMaes1.jpg",
    "POI_Image3": "DixieMaes2.jpg",
    "POI_Image4": "DixieMaes3.jpg",
    "POI_Image5": "",
    "POI_Image6": "",
    "POI_Address1": "634 W Main St",
    "POI_Address2": "",
    "POI_City": "Sylva",
    "POI_State": "NC ",
    "POI_ZipCode": 28779,
    "POI_ContactName": "",
    "POI_Phone": "828-586-8866",
    "POI_URL": "https://www.dodieallen.com",
    "POI_Category": "1",
    "POI_PetFriendly": false,
    "POI_Image1_Desc": "",
    "POI_Image2_Desc": "",
    "POI_Image3_Desc": "",
    "POI_Image4_Desc": "",
    "POI_Image5_Desc": "",
    "POI_Image6_Desc": ""
}]